apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: partner-endorser-acme
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-endorser-acme
  chart:
    path: examples/identity-app/charts/acme
    git: https://github.com/Talha089/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      namespace: partner-ns
      name: partner-endorser
    organization:
      name: partner
    image:
      pullSecret: regcred
      init:
        name: certs-init
        repository: alpine:3.9.4
      agent:
        name: partner-endorser
        repository: index.docker.io/sownak/aries-agents:1.11.0
    service:
      ports: 
        service: 15033
        endpoint: 15034
        webhook: 15035
      
      address: partner-endorser.indy.crowdpoint.tech
      
      ledger: http://softtik-webserver.indy.crowdpoint.tech:15010
      genesis: http://softtik-webserver.indy.crowdpoint.tech:15010/genesis
    vault:
      address: http://a8f18618947b649ec88a29aaf08fa3d2-695861177.us-west-1.elb.amazonaws.com:8200
      serviceAccountName: partner-partner-endorser-vault-auth
      authPath: kubernetes-partner-partner-endorser-auth
      endorserName: partner-endorser
      role: ro
    storage:
      size: 128Mi
      className: partner-aws-storageclass
    proxy:
      
      provider: "ambassador"
